from enum import Enum


class ConversationState(str, Enum):

    START = "START"

    COLLECTING_REQUIREMENTS = "COLLECTING_REQUIREMENTS"

    READY_FOR_RETRIEVAL = "READY_FOR_RETRIEVAL"

    RETRIEVING = "RETRIEVING"

    RECOMMENDING = "RECOMMENDING"

    COMPLETED = "COMPLETED"